version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ecopulse-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ecopulse-net

  grafana:
    image: grafana/grafana:latest
    container_name: ecopulse-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=debug
    volumes:
      - C:/Users/Simay/source/repos/EcoPulse/dashboards.yml:/etc/grafana/provisioning/dashboards.yml
      - C:/Users/Simay/source/repos/EcoPulse/ecopulse_forecast.json:/etc/grafana/provisioning/dashboards/ecopulse_forecast.json
    networks:
      - ecopulse-net

networks:
  ecopulse-net:
    driver: bridge
