global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'ecopulse_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5080']

  - job_name: 'ecopulse_worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9105']
